version: '3.8'

services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webhook-network

  redis-pubsub:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webhook-network

  webhook-processor:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
      - redis-pubsub
    networks:
      - webhook-network
    volumes:
      - ./:/app

networks:
  webhook-network:
    driver: bridge
